### ISSUE TITLE
Is supportedCountries sufficient?

### ISSUE THREAD

**Issue by mattsaxonwp** [w3c/webpayments-methods-credit-transfer-direct-debit#33]
Whilst a merchant might say they accept payments from various, countries, I'm not sure we can lose the supportedNetworks field.

An example would be, what is the payment application only supports SEPA or what if the bank account only accepts payments via BACS (UK network), but not CHAPS (another UK network).

I don't see how a PaymentApplication can choose the correct route or indeed decide if a route exists without this.

Furthermore, different netowkrs have different costs, e.g. CHAPS in the UK has a £30 cost per transaction and is generally used for high value payments as a result.

**Comment by CYV** [comment]
I strongly recommend that we have both countries AND network of payments (my own vocabulary is "scheme"). For the SEPA push mechanisms, we have :
- SEPA Credit Transfer
_ SEPA instant payment (next !)

**Comment by ianbjacobs** [comment]
Based on discussion on 2 Feb, we added back supportedNetworks:
https://github.com/w3c/webpayments-methods-credit-transfer-direct-debit/pull/35
