### ISSUE TITLE
ISO 3611-2 vs. CLDR

### ISSUE THREAD

**Issue by adamroach** [w3c/webpayments-methods-credit-transfer-direct-debit#34]
The `PaymentAddress` interface [defined in the Payment API](https://w3c.github.io/browser-payment-api/#paymentaddress-interface) has a `country` attribute that is defined as being the "the CLDR (Common Locale Data Repository) region code."

This specification proposes using ISO3166-2 for the `CreditTransferRequest.supportedCountries` field. While these are largely harmonized, they technically are different authorities, and I'm concerned about the prospect of having to deal with two different databases of largely the same information within a single body of specification.

I don't have enough background to know whether there is a single specification that is favored for W3C specs. If so, we should ensure that all the payments work uses that. In the absence of such precedent, we should at least use only one authority within the payments-related specifications.

**Comment by adamroach** [comment]
Note that I'm filing the issue on this spec, but that doesn't necessarily mean that this is the one that needs to change -- this may well be something that requires a change in the Payment API instead. What's important is consistency.

**Comment by ianbjacobs** [comment]
Changed to CLDR for consistency with PR API
https://github.com/w3c/webpayments-methods-credit-transfer-direct-debit/pull/36
