### ISSUE TITLE
A number of the transaction types require data to be supplied in the Request 

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-credit-transfer-direct-debit#4]
At the moment, the spec has no data sent to the payment application and all the data is returned in the response.

Whilst this is correct for ST and DD methods where there is no linking, the text suggests that for SCT and SDD, that the merchant providers data to the payment application.

This should be represented by a Request structure in section 4 of the specification.

**Comment by CYV** [comment]
I aggree, we should set additional data in the request structure.

for the SCT payments, the merchant should provide in the request:
- remittance information
  -Iban of the merchant
- BIC related to the IBAN of the emrchant
- beneficiary identification code
- Name of the beneficiary
- purpose of the credit transfer
- category purpose of the credit transfer
  date of initiation

For the SDD CORE, the merchant should provide in the request:
- transaction type (one-off / recurent)
- identifier of the creditor (ICS of the merchant : it must have one according to the rules of SDD SCheme)
- remittance information
- purpose of collection
- category purpose of collection
- unique reference of mandate

**Comment by mattsaxon** [comment]
I've updated the specification as per the above. There's lots of details to discuss on Wedneday, but the basic format of the document is ok I believe.
