### ISSUE TITLE
Use of WebIDL in payment method specifications

### ISSUE THREAD

**Issue by cyberphone** [w3c/webpayments-methods-credit-transfer-direct-debit#40]
AFAIK, WebIDL is a language which has been developed primarily to describe data and methods in Web browsers.  Unless a specification is to to be natively implemented in browsers, it seems that the language we are dealing with rather is JSON/JSON-serializable JavaScript.  The more common way is describing such schemes is JSON-Schema, Swagger or just simple tables with types String, Number, Boolean.  Most business system programmers have probably never even heard about WebIDL and I don't think they should worry about that either :-)

**Comment by ianbjacobs** [comment]
We do not know in advance whether a browser will implement this specific natively. 
It is also the case, for example, in the Tokenization specification that a payment
method specification could inherit data structures from another specification. 
I think that this time we gain by having consistency in the approaches taken by
the W3C payment method specifications. If we find that developers of payment
apps for these specifications require an alternative presentation of the spec's
requirements, we can certainly change the specs.

I'll leave this issue open for now. However, if there is positive feedback on the shape
of the spec from developers at the WG's upcoming FTF meeting I will be inclined
to close this issue.

**Comment by adrianhopebailie** [comment]
This has been discussed and closed. I don't believe there is any new information here: https://github.com/w3c/webpayments/issues/133
