### ISSUE TITLE
Spec is missing flow

### ISSUE THREAD

**Issue by mattsaxon** [w3c/webpayments-methods-credit-transfer-direct-debit#5]
The PMI for CT-DD is missing a flow diagram

**Comment by CYV** [comment]
Matt,
you expect a flow describing the SCT  and another one for the SDD ?

**Comment by mattsaxon** [comment]
Yes I think so. You may already have defined this in the original flows work though. I'm just suggesting it needs putting in the spec as per the basic card example which now has such a flow

**Comment by mattsaxon** [comment]
I've added placeholders for the flows and update the CT one to be correct. We can discuss the SCT one this coming Wednesday.
